# Generated by Django 3.0.3 on 2020-02-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_query_name='site_configurations', to='auth.Group'),
        ),
    ]
